# Generated by Django 5.1.2 on 2025-04-15 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trieda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Trieda',
                'verbose_name_plural': 'Triedy',
                'ordering': ['nazov'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meno', models.CharField(max_length=20)),
                ('priezvisko', models.CharField(max_length=30)),
                ('trieda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='newapp.trieda')),
            ],
            options={
                'verbose_name': 'Študent',
                'verbose_name_plural': 'Študenti',
                'ordering': ['priezvisko'],
            },
        ),
        migrations.CreateModel(
            name='Ucitel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titul', models.CharField(max_length=20)),
                ('meno', models.CharField(max_length=20)),
                ('priezvisko', models.CharField(max_length=30)),
                ('trieda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='newapp.trieda')),
            ],
            options={
                'verbose_name': 'Učiteľ',
                'verbose_name_plural': 'Učitelia',
                'ordering': ['priezvisko'],
            },
        ),
    ]
